# which benchmarks to run
benchmarks = '../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.task2]
pipeline = [
  "bril2json",
  "python constant.py",
  "python lvn.py",
  "python liveness_dce.py",
  "brili -p {args}",
]

[runs.task3]
pipeline = [
  "bril2json",
  "python normalize_loops.py",
  "python to_ssa.py",
  "python licm.py",
  "python constant.py",
  "python lvn.py",
  "python liveness_dce.py",
  "python from_ssa.py",
  "brili -p {args}",
]

[runs.task4]
pipeline = [
  "bril2json",
  "python dse.py",
  "python store_forwarding.py",
  "python rle.py",
  "python constant.py",
  "python lvn.py",
  "python liveness_dce.py",
  "brili -p {args}",
]