# which benchmarks to run
benchmarks = '../benchmarks/mem/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.task4]
pipeline = [
  "bril2json",
  "python dse.py",
  "brili -p {args}",
]