# which benchmarks to run
benchmarks = '../benchmarks/mem/adj2csr.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.task2]
pipeline = [
  "bril2json",
  "python constant.py",
  "python lvn.py",
  "python liveness_dce.py",
  "brili -p {args}",
]

[runs.inline]
pipeline = [
  "bril2json",
  "python utils/inline/optimal.py",
  "python constant.py",
  "python lvn.py",
  "python liveness_dce.py",
  "brili -p {args}",
]