# which benchmarks to run
benchmarks = '../examples/test/tdce/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p",
]

[runs.best]
pipeline = [
  "bril2json",
  "python remove_nops.py",
  "python lvn.py",
  "python global_dce.py",
  "python local_dce.py",
  "brili -p",
]
